### ISSUE TITLE
Constants are a mess

### ISSUE THREAD

**Issue by nicholas-miklaucic** [nicholas-miklaucic/scarlet#16]
The `consts.rs` file runs into the problem that, as of now, Rust doesn't allow constants or statics to use functions to initialize. This means that every time we do any conversion, we generate the matrix from scratch, or do that *and take its inverse*. This is ridiculous, but it's hard to think of ways to fix it. We could add `const fn`, which is a nightly feature, but I'm unsure if that will even apply. We could store the inverses, but unless we do it to something like 15 decimal places we'll lose the preciison that made me use this library in the first place.

**Comment by ErichDonGubler** [comment]
Have you looked at [`lazy-static`](https://github.com/rust-lang-nursery/lazy-static.rs)? It sounds like it would fit your use case since compile-time matrix generation isn't an option.

**Comment by nicholas-miklaucic** [comment]
Thanks for the info! I didn't know about this, but it solves my problem. Resolved as of [this commit.](https://github.com/nicholas-miklaucic/scarlet/commit/e650ca7ab2d3723e22732f88f52e4d852dfe85d2)
