### ISSUE TITLE
Add Material Design color palette to Scarlet

### ISSUE THREAD

**Issue by nicholas-miklaucic** [nicholas-miklaucic/scarlet#26]
It'd be awful nice to be able to easily access the colors at [Google's Material Design site](https://material.io/guidelines/style/color.html).

**Comment by milesmcc** [comment]
> It'd be awful nice

It's almost as if you were just really _trying_ to tag @milesmcc but couldn't bring yourself to!

**Comment by nicholas-miklaucic** [comment]
It'd be awful nice is all I'm saying!

**Comment by nicholas-miklaucic** [comment]
Closed because of most recent commit.
