### ISSUE TITLE
Use deps.rs?

### ISSUE THREAD

**Issue by nicholas-miklaucic** [nicholas-miklaucic/scarlet#29]
Title.

**Comment by nicholas-miklaucic** [comment]
I don't even know what this is or how to use it. Tabled for later.

**Comment by ErichDonGubler** [comment]
You'd want this: https://deps.rs/repo/github/nicholas-miklaucic/scarlet

**Comment by nicholas-miklaucic** [comment]
Gotcha. Thanks for the help! Updated and added badge to README, so closing this as of last commit.
