### ISSUE TITLE
Intra-crate links break in docs.rs

### ISSUE THREAD

**Issue by nicholas-miklaucic** [nicholas-miklaucic/scarlet#35]
Docs.rs is breaking the intradoc links in many places. They work fine in local docs, though. Something to look into further. Hopefully soon the RFC on this will be stabilized so I can avoid this mess.

**Comment by nicholas-miklaucic** [comment]
Should be fixed: we'll see.

**Comment by milesmcc** [comment]
:tada:

**Comment by nicholas-miklaucic** [comment]
Solved!
