### ISSUE TITLE
Link to API.org Seems Wrong

### ISSUE THREAD

**Issue by tajmone** [nicholas-miklaucic/scarlet#40]
In the README you state:

> To look at the general philosophy and API design of Scarlet, please look at `api.org`. This is more intended for developers.

The domain www.api.org points to the American Petroleum Institute, a website dedicated to natural gas and oil.

Which was the originally intended reference for API guidelines?

**Comment by nicholas-miklaucic** [comment]
This was intended to link to the api.org document in the source. I promise I'm not being paid off by Big Petroleum.

**Comment by tajmone** [comment]
> This was intended to link to the `api.org` document in the source. 

I was giving for granted that the `.org` was a domain extension pointing to some website that I'd missed the (rather obvious) connection to the `api.org` file! 😳 

Might be worth converting that into a document link though: [`api.org`](../blob/master/api.org)

```markdown
please look at  the [`api.org`](./api.org) document.
```

> I promise I'm not being paid off by Big Petroleum.

I take your word on that! 😉
