### ISSUE TITLE
Different kinds of gradients

### ISSUE THREAD

**Issue by nicholas-miklaucic** [nicholas-miklaucic/scarlet#7]
We currently just have linear gradients. It's sometimes nice to have other kinds, such as:

 - Logarithmic
 - Square root/cube root
 - Padding the scale on either end (e.g., end 80% of the way there)

These should be easy to implement and are a good way to get started!

**Comment by milesmcc** [comment]
I suggest that this issue now be closed, now that #22 and #23 have added cube root gradients and padded gradients, respectively.

(And logarithmic gradients might break the library's design ideology—possible negative/impossible values—so those shouldn't be implemented; decided in-person.)
